# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d53cf943a82876e918c272dfc5dc64d629b7b237783800b25b4bca201e1b4234946da7c83dd1620c42d869bd4363cec137cd859dfb56ba350daf9c3900b1a4f2

test:
  secret_key_base: 8df5d7685acc6b9f4dd3586eb3a3d1075ad8e270f8f7d68adeaa1e3a900f5b8d440d1d64008a7058fc03473630aec1bdc4cd7f800715e50863387be8bf29a672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
